### ISSUE TITLE
Opening snowfile with relative paths uses executable pwd

### ISSUE THREAD

**Issue by mmm2mmm** [Soothsilver/snowride#102]
When opening  snowfile with relative paths is used executable pwd as the base for relative paths.  It is in contradiction with functonality "Open snowfile"  in main menu  That makes useless dialog with folder selection.

My expected behavior would be open the snowfile anywhere it is stored and relative paths would be to location of the snowfile. Currently i am getting following error

java.lang.RuntimeException: The file 'C:\Sofware_NoInstaller\src\test\robot\tests' is not a directory.
        at cz.hudecekpetr.snowride.parser.GateParser.loadDirectory(GateParser.java:45)
        at cz.hudecekpetr.snowride.ui.MainForm.lambda$loadProjectFromFolderOrSnowFile$61(MainForm.java:871)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

When changing this, storage of the snowfile would have to change its behavior or be parameterized.

**Comment by Soothsilver** [comment]
I think Snowride takes the current directory as the relative base. So if you open Snowride directly and then open the snow file from within, it will not work (as you demonstrated). But, if you double-click the .snow file (and have .snow associated with Snowride), then your OS will open Snowride in that directory and it will work.

That said, I agree that using the snow file's directory as the relative base is better. I would be happy to merge such a change in if you make a pull request for it. You probably want to make changes at snowride.settings.SnowFile#32: https://github.com/Soothsilver/snowride/blob/c731292d0cebd38588cb5b28ca4dde8f90183169/src/main/java/cz/hudecekpetr/snowride/settings/SnowFile.java#L32 or somewhere around there.

**Comment by vehovsky** [comment]
This should do the trick, resolving relative paths (relative to .snow file) in:
Directory
AdditionalPaths
RunnerScript
