### ISSUE TITLE
Some built-in keywords are incorrectly showing the wrong numbers of arguments

### ISSUE THREAD

**Issue by vitorego** [Soothsilver/snowride#111]
Using the new SnowRide 3.1 some built-in keywords are being set with red cells indicating that there is no more arguments:
![image](https://user-images.githubusercontent.com/28743244/171381698-a939777f-856b-48f4-a27a-c5af382b29b0.png)

**Comment by vehovsky** [comment]
Thanks for reporting this issue.

Can you please test this SNAPSHOT if you will not find any similar issues.

https://github.com/Soothsilver/snowride/releases/download/release-v3.2-SNAPSHOT/snowride-3.2-SNAPSHOT-jar-with-dependencies.jar

Thanks

**Comment by vitorego** [comment]
It is fixed with that SNAPSHOT.
![image](https://user-images.githubusercontent.com/28743244/171836748-970a3f66-0efe-407c-9041-a5c108feef62.png)

Thanks
