### ISSUE TITLE
Reload-on-change

### ISSUE THREAD

**Issue by Soothsilver** [Soothsilver/snowride#27]
When files change on the filesystem, Snowride should ask the user to reload the files.

**Comment by Soothsilver** [comment]
done

**Comment by Chevalier-Maxime** [comment]
Hi, is it possible to add a parameter to set auto-reload on changes ?

**Comment by Soothsilver** [comment]
Is #73 what you have in mind? Or do you maybe have some specific changes that you want to be ignored?

**Comment by Chevalier-Maxime** [comment]
No #73 could be nice to have, but I was thinking of an automatic reload without popup or key pressing (we modify files in excel multiples times before launching an actual test in snowride).

**Comment by Soothsilver** [comment]
I'm a little worried about autoreloading because what if the file is still being used by Excel when Snowride receives the notification when it changes. But it should probably be fine since it's being open just for read access. Did I understand it right in #75 ?

**Comment by Chevalier-Maxime** [comment]
Yes, #75 would be perfect, thanks.

Perhaps, when using the popup, it should appear when focusing back to snowride (it may ease the utilization with other editors like excel) ?

Also, I think the reload shouldn't deselect selected tests.

**Comment by Soothsilver** [comment]
These are good suggestions, but neither is very simple to implement given the code in Snowride already, I think. You can create them as issues and maybe @martzz or somebody else will pick them up. The second issue especially would take a couple of hours. We would need to do something similar to what we do for keeping the open test open when you reload, but more efficient.

**Comment by Chevalier-Maxime** [comment]
Thank you for release 2.5 👍 it really ease our process.
