### ISSUE TITLE
Possible issue with directory naming?

### ISSUE THREAD

**Issue by HW71** [Soothsilver/snowride#67]
Hi all,

just gave both Snowride 1.8 and 2.2 a try and ran into the following problem:

Our test directory structure uses numbers + underscores in order to have some kind of sorting, e.g.

1__startup
2__entryTests
3__mainTests
...

Now when I try to run one test from the "3__mainTests" suite I get the following error:

`> C:\RobotFramework\Python27-64\Scripts\pybot.bat --argumentfile C:\..\Temp\Snowride3966344366248579491\argfile1241499702101165572.txt --listener C:\..\Temp\Snowride3966344366248579491\TestRunnerAgent.py:63222:False -V C:\..\myVariables.py C:\..\testcases\3__mainTests[ ERROR ] Suite 'mainTests' contains no tests named '3  mainTests.soap.Basic.my.Test' in suite '3  mainTests.soap.Basic.my.Test'.`

As can be seen from the Log, the "__" characters from directory "3__mainTests" have been replaced by Space characters, and this might be the cause for not finding the test case. :-(

Is this an issue with the directory naming - or is this a bug in Snowride? At least RIDE doesn't have an issue with this (but OK - maybe that's a big in RIDE ;-)  ).

Thanks so much in advance & kind regards!

-Erik

**Comment by Soothsilver** [comment]
A bug in Snowride.

The Robot Framework User Guide says:

> The file or directory name can contain a prefix to control the execution order of the suites. The prefix is separated from the base name by two underscores and, when constructing the actual test suite name, both the prefix and underscores are removed. For example files _01__some_tests.robot_ and _02__more_tests.robot_ create test suites _Some Tests_ and _More Tests_, respectively, and the former is executed before the latter.

I tried to fix it in Snowride 2.3. Reopen this issue if it doesn't work for you.

**Comment by HW71** [comment]
Awesome - works like a charm now! :-)

Thanks for the quick fix - will now do some further checks in order to see if we have similar issues like this "freeze" of RIDE in combination with Windows 10. For now things look promising!

Cheers, Erik
