### ISSUE TITLE
Delete cells missing in context menu

### ISSUE THREAD

**Issue by martzz** [Soothsilver/snowride#68]
While deleting the whole rows is possible, the delete cells is not (with automatic shift of the following cells to the left).

**Comment by Soothsilver** [comment]
Does this have a keyboard shortcut in RIDE or is this just for the context menu?

Proposed spec: "Add a context menu item 'Delete cells and shift row left' which erases the contents of all selected cells, and, for each affected row, starting from the rightmost deleted cell and continuing left, shifts the contents of all cells to the right of that cell by one to the left. 

This should work even if the user selects two cells in a single row which are not adjacent to each other. 

This entire action is a single undoable mass text change operation."

**Comment by martzz** [comment]
**Insert Cell**: Ctrl + Shift + I
**Delete Cell**: Ctrl + Shift + D
Both actions are accessible also from the context menu. I think we should support both. Today I was editing an XRS robot with extremely long rows and in such situation this feature is very handy.

I can start working on this, but if you want it, it's yours. Assign it to somebody ;)

**Comment by Soothsilver** [comment]
Then it's yours ^^. Context menu is in `buildContextMenu`. Keyboard shortcuts are in `SnowTableView`. An example of how to do a mass undo stack operation and an operation on multiple cells is in implementation of Cut (Ctrl+X).

**Comment by martzz** [comment]
Insert/delete cell implemented. Multi-selection and undo/redo operations supported. This all is going to 2.8.
