### ISSUE TITLE
File format / line ending changed after save...

### ISSUE THREAD

**Issue by HW71** [Soothsilver/snowride#69]
Hi there,

our Robot files are usually saved in Windows format using CR/LF. However, once a file gets edited with Snowride and saved, the format of the line ending appears to have been changed to UNIX / LF.

It would be great to have an option in the settings, that allows users to at least keep the current format.

Kind regards & Cheers, Erik

**Comment by Soothsilver** [comment]
Strange. Snowride should keep the line endings of files (and use Unix for
new files). I ll look into it when I get back to a computer in two weeks.

Perhaps the best option would be to add a switch between crlf/lf/keep,
which I think is what RIDE has.

**Comment by Soothsilver** [comment]
Fixed in 2.4.

**Comment by HW71** [comment]
Awesome - thanks a lot! 👍
