### ISSUE TITLE
libraries fail to load in snowride but they are perfectly fine in RIDE

### ISSUE THREAD

**Issue by raghu19991** [Soothsilver/snowride#70]
The snowride version fails to load custom libraries and some core libraries as well from the site-packages of python(2.7) into the test suite.
It executes it nonetheless but it is just that if it doesn't load we cannot get search help when you enter atrl+space nor we are able to redirect to the keyword definition on double click.

![image](https://user-images.githubusercontent.com/13601882/61688496-48784380-ad79-11e9-822b-d8a4e9e66215.png)
![image](https://user-images.githubusercontent.com/13601882/61688509-54640580-ad79-11e9-8583-22803b9947d1.png)

![image](https://user-images.githubusercontent.com/13601882/61688628-a573f980-ad79-11e9-9811-f7ae3af74da4.png)

**Comment by Soothsilver** [comment]
Good idea.
Spec:
When you open a file keyword, test case or suite that imports an unknown library that hasn't been loaded from a file in one of the directories in Snowride's Settings, check if it can be loaded by Python's libdoc (which it will if it's on the system PYTHONPATH, including in site-packages. If it can, libdoc it, import it, and reload the current high element.

**Comment by Soothsilver** [comment]
Fixed in 2.4.

**Comment by raghu19991** [comment]
I see the build failed
[image: image.png]

**Comment by Soothsilver** [comment]
It did fail on Travis CI, but I could build and deploy from my own computer fine. If you have an idea on why it doesn't work on Travis anymore, I'm listening, because I'm stumped. It's as if it's missing javafx from classpath somehow?
