### ISSUE TITLE
Better navigation: map 'backwards' and 'forwards' buttons to key binding

### ISSUE THREAD

**Issue by voracfil** [Soothsilver/snowride#71]
The navigation in history is a necessary thing for all good IDEs. SnowRide already provides buttons for such a thing, but it would be nice to enable to map this functionality into quick keys.

In Eclipse and RIDE, this is mapped to ALT+left/right arrow. Either hardcode it to these values, or provide an option to do a key binding.

**Comment by Soothsilver** [comment]
Actually, it's Ctrl+Alt+Left in RIDE and Snowride already has the same
keyboard shortcuts.

I ll leave this item open for the cudtomizstion of mapping.

**Comment by Soothsilver** [comment]
Spec:
In addition to allowing Ctrl+LEFT and Ctrl+RIGHT for navigation, also accept Alt+LEFT and Alt+RIGHT. Holding Alt like this should not focus the main menu bar.

**Comment by Soothsilver** [comment]
Fixed in 2.4.
