### ISSUE TITLE
Change in shorcut keys

### ISSUE THREAD

**Issue by raghu19991** [Soothsilver/snowride#72]
It would be good to have an option of changing the shortcut keys using the UI since most people are familiarised with the shortcut keys of RIDE like Ctrl+3 to comment and Ctrl+4 to uncomment and so on.Is it possible to have that option?

**Comment by Soothsilver** [comment]
Yes, but I dont have time to implement it myself. I can add all RIDE
shortcuts as alternstives, though. Could someone please make a list of
missing/different shortcuts?

**Comment by Soothsilver** [comment]
Added in 2.5, but my system doesn't register Ctrl+3 and Ctrl+4 (among several other combinations as well). This may have something to do with those combinations being used for switching keyboard layouts or being already registered by some other application (GeForce Experience, maybe?). So, it may not work for you, either.
