### ISSUE TITLE
Enhance snow files

### ISSUE THREAD

**Issue by Chevalier-Maxime** [Soothsilver/snowride#74]
Currently snow files can only be used to configure Directory, RunnerScript and AdditionalPaths parameters. It would be nice to add other parameters like (using settings.xml names) : 
* runArguments
* tbWithoutTags
* tbWithTags
* cbWithoutTags
* cbWithTags

So it will be easier to manage multiple projects with different configurations.

**Comment by Soothsilver** [comment]
Added in 2.5. There are downsides to this as well: when you make a change, it won't be remembered (unless you save it explicitly into the .snow file again).
