### ISSUE TITLE
Can we ignore Given,When,Then,And  - gherkin related keywords when they are entered before the keyword

### ISSUE THREAD

**Issue by raghu19991** [Soothsilver/snowride#76]
Currently the keywords are not identified if Given,When,Then and AND are used before it.
Could we maybe ignore the usage of these words initially and identify the keywords after that?
![Gherkin](https://user-images.githubusercontent.com/13601882/63658461-c0191280-c7fe-11e9-8d70-c890553d95c8.PNG)

**Comment by Soothsilver** [comment]
A good idea. It's not super trivial because of how it interacts with autocompletion, though. Probably it should work similarly to how libraries work. I think that's how it works in RIDE? I'll see if I can do it during the weekend.

**Comment by Soothsilver** [comment]
Would you try out 2.6 to see if it works, please?

Link:
[![Download](https://api.bintray.com/packages/snowride/snowride/snowride/images/download.svg?version=2.6)](https://bintray.com/snowride/snowride/download_file?file_path=cz%2Fhudecekpetr%2Fsnowride%2Fsnowride%2F2.6%2Fsnowride-2.6-jar-with-dependencies.jar)

**Comment by raghu19991** [comment]
Sure .will try and let you know

**Comment by raghu19991** [comment]
it is working fine.
when you open the application and navigate to any test case,then the empty cells(greyed) keeps on expanding to the right.Not sure why that is happening.
But apart from that everything else is working fine

**Comment by Soothsilver** [comment]
Thanks.
I don't understand the other bug. Could you upload a screenshot, please?

**Comment by Soothsilver** [comment]
Fixed in 2.6.
