### ISSUE TITLE
Delete cell and add cell functionality

### ISSUE THREAD

**Issue by raghu19991** [Soothsilver/snowride#80]
Currently snowride only has functionality to add a new row or delete a row.
Could you please also add functionality to 
add a cell(creates a cell to right and pushes all the content after it(if any) to the right of the newly created cell) 
delete a cell(deleted the selected cell and moves the content after the cell(if any), 1 cell to the left)

**Comment by Soothsilver** [comment]
This is the same as #68 but also for Insert. I know of this and I agree. It's a good idea to implement it.

**Comment by martzz** [comment]
Duplicate of #68
