### ISSUE TITLE
Shared robot keywords (defined in Settings) not loaded correctly

### ISSUE THREAD

**Issue by martzz** [Soothsilver/snowride#81]
![Screenshot from 2019-10-09 16-56-24](https://user-images.githubusercontent.com/49608327/66493570-936f4080-eab6-11e9-96e4-fd95554dea89.png)
![Screenshot from 2019-10-09 16-57-10](https://user-images.githubusercontent.com/49608327/66493595-9f5b0280-eab6-11e9-96c6-4d3bd434eaa8.png)
![Screenshot from 2019-10-09 16-57-35](https://user-images.githubusercontent.com/49608327/66493617-a71aa700-eab6-11e9-80ba-6dd7da265879.png)

**Comment by martzz** [comment]
Resource loading has been aligned with the way how it works in RIDE.

@Soothsilver please review

**Comment by Soothsilver** [comment]
I'll look at it over the weekend, and it makes sense, but I thought I went over all of your team's robot files and fixed in RIDE anything that was a problem. Probably I missed it. It doesn't look like something caused by Linux.

**Comment by martzz** [comment]
Thanks, I have already fixed this one (7d8ba9f8c79dd4f2cfa08018c400847cd5512780).

Please provide code review if you have time.

**Comment by Soothsilver** [comment]
It seems weird  -- it should have already worked. But if you tested it, and it didn't work without the change and works with it, then great.

**Comment by martzz** [comment]
It didn't work because it took 'resources' section from the Path and compared it with 'actions' and it didn't go any deeper.
