### ISSUE TITLE
*** Keyword *** element not interpreted correctly

### ISSUE THREAD

**Issue by martzz** [Soothsilver/snowride#82]
*** Keywords *** is ok, but in RIDE, also *** Keyword *** is possible.

![Screenshot from 2019-10-09 17-22-02](https://user-images.githubusercontent.com/49608327/66495436-8273fe80-eab9-11e9-882a-f4b05221b9a5.png)

**Comment by martzz** [comment]
Old robot tests updated - no fix.

**Comment by Soothsilver** [comment]
I'm going to reopen and possibly fix; the user guide says "In addition to using the plural format, also singular variants like Setting and Test Case are accepted."

**Comment by Soothsilver** [comment]
Fixed in 2.7.
