### ISSUE TITLE
Log and Report buttons cause complete app freeze (linux)

### ISSUE THREAD

**Issue by martzz** [Soothsilver/snowride#84]
no output taken - to be further investigated

**Comment by Soothsilver** [comment]
The code is `Desktop.getDesktop().open(new File(filename));`

Maybe it locks down if the file is locked or doesn't exist?

**Comment by vehovsky** [comment]
Fixed https://github.com/Soothsilver/snowride/commit/d5f526ac1acb19c449820d98e44e81895c3d4934
