### ISSUE TITLE
Navigation in Text edit by Ctrl-Left Ctrl-Right

### ISSUE THREAD

**Issue by alex-iongroup** [Soothsilver/snowride#91]
Would be really nice to have navigation by a word when using Text edit, like in almost every text editor.

**Comment by vehovsky** [comment]
Fixed. https://github.com/Soothsilver/snowride/commit/8357f9318e9f9510e83d8e5a2e4acc905be64027

removed global key bindings for CTRL+LEFT/RIGHT (used for navigate back/forwards)
 - in general other editors are not using such keybinding
 - prevents navigating using CTRL in TextArea
