### ISSUE TITLE
Load directory is always defaulted to the highest level

### ISSUE THREAD

**Issue by alex-iongroup** [Soothsilver/snowride#95]
When opening a directory by Project -> Load directory... the directory tree selector always starts from the highest level - the PC on Windows. 

Would be really nice if the selector could remember the last opened directory and could show it when opening a new directory. At least this is the behaviour of all of IDEs I use.
![image](https://user-images.githubusercontent.com/20903137/75327878-6234b880-587d-11ea-8de9-3b401e326def.png)

**Comment by vehovsky** [comment]
Fixed. https://github.com/Soothsilver/snowride/commit/7e78c82ee7fc25a8387d6add8e7f34c03f36194c
