### ISSUE TITLE
Selection of a Keyword is lost when switching to the Text Edit and back

### ISSUE THREAD

**Issue by alex-iongroup** [Soothsilver/snowride#96]
Steps to reproduce.
1. Select a keyword in the Tree
![image](https://user-images.githubusercontent.com/20903137/75334677-8f3a9880-5888-11ea-8252-e033bca3f120.png)
2. Switch to the Text edit
![image](https://user-images.githubusercontent.com/20903137/75334715-9f527800-5888-11ea-9d2b-ea6d2de53e64.png)
3. Switch back to the Assisted grid editing
![image](https://user-images.githubusercontent.com/20903137/75334773-b5f8cf00-5888-11ea-8662-54177aa4fc09.png)

Result:
The whole suite is selected and the suites settings are shown in the grid

Expected result:
The keyword should be shown again

**Comment by vehovsky** [comment]
Fixed in https://github.com/Soothsilver/snowride/commit/78e456ef05d839e9abbcebef9ec0377c94c2a7af

**Comment by vehovsky** [comment]
Unfortunately the solution was too naive. Reopening

**Comment by vehovsky** [comment]
second time's a charm 55b40392f1c29a03b9460dc78bab5420043e5b23
