### ISSUE TITLE
Undo does not work correctly

### ISSUE THREAD

**Issue by voracfil** [Soothsilver/snowride#97]
Hi,

Undo does not work properly and might delete some arbitrary parts of text.

Test case:
1) Open some robot file
2) Add some new lines in the middle (CTRL+I)
3) Write a new line somewhere
4) Save the file - snowride will reformat the file (empty lines are removed etc.)
5) Undo (CTRL+Z) - Undo does not work correctly, might throw OutOfBoundException (better), or might delete some arbitrary lines from robot file (much worse)

As such, undo is a very dangerous operation at the moment.

Thanks,
Filip

**Comment by vehovsky** [comment]
Hi Filip,

This should do the trick: https://github.com/Soothsilver/snowride/commit/83632fbde06d1b21c271c65dd5d92fcb3d1fc025

BR
M.
