### ISSUE TITLE
Error report of execution case

### ISSUE THREAD

**Issue by wh9204** [Soothsilver/snowride#99]
When I try run case.Snowride Provide error report for me
Should I require sth configuration files setting?

![image](https://user-images.githubusercontent.com/17823780/93309101-b319f780-f835-11ea-8830-2c88d32fb0ff.png)

**Comment by Soothsilver** [comment]
You need to create a script file (a .bat file on Windows) and put it in the "Script:" text field in the Run tab.

The script file should contain something like "python -m robot.robot" Snowride will append its arguments after that.

**Comment by wh9204** [comment]
> You need to create a script file (a .bat file on Windows) and put it in the "Script:" text field in the Run tab.
> 
> The script file should contain something like "python -m robot.robot" Snowride will append its arguments after that.


@Soothsilver 
Thanks.That slove my issue.
But when I try running my testsuit files it always run all cases instead selected case.
This brings up another issue I can't stop case to run.
Do you have some advise for me?
Thanks a lot

**Comment by Soothsilver** [comment]
Ah, yes, sorry, I gave you wrong advice.

Either put "python -m robot.robot  %*" into your batch file so that arguments sent by Snowride to the batch file are passed to the Robot Framework.

If that doesn't work, send me a screenshot and the output and I'll look at it over the weekend.
